### ISSUE TITLE
Import Error No module named 'requests'

### ISSUE THREAD

**Issue by N00D13** [install-logos/ricedb#70]
I got these Error:

``` shell
[root@shell ricedb]# rice
Traceback (most recent call last):
  File "/usr/bin/rice", line 2, in <module>
    from ricedb import ricemain 
  File "/usr/lib/python3.4/site-packages/ricedb/ricemain.py", line 2, in <module>
    import json, os, argparse, requests
ImportError: No module named 'requests'
```

**Comment by N00D13** [comment]
Sorry my fault.

``` shell
pip install requests
```
